### ISSUE TITLE
CLI Not working

### ISSUE THREAD

**Issue by Parthtrap** [MrMysterius/nhentai-download-cli#3]
Either I am not able to understand what CLI means or its not working for me but after I install the file using
`npm i -g MrMysterius/nhentai-download-cli`
I cant seem to do anything with it... if I try to run the command `nhenaitdl download -i <nhentai ID>`

the message I get is...

``` nhenaitdl : The term 'nhenaitdl' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nhenaitdl
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nhenaitdl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

in Powershell 

and

```'nhenaitdl' is not recognized as an internal or external command,
operable program or batch file.
```

in CMD...

Please tell me where I am wrong and how to actually use this CLI

**Comment by Parthtrap** [comment]
NVM... After using some brain i saw that its actually a typo in readme... but still its not working... 
I am getting this following message...

```
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/manipulation' is not defined by "exports" in C:\Users\mttpa\AppData\Roaming\npm\node_modules\nhentai-download-cli\node_modules\cheerio\package.json
←[90m    at new NodeError (internal/errors.js:322:7)←[39m
←[90m    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)←[39m
←[90m    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)←[39m
←[90m    at resolveExports (internal/modules/cjs/loader.js:450:36)←[39m
←[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)←[39m
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:93:18)←[39m
    at Object.<anonymous> (C:\Users\mttpa\AppData\Roaming\npm\node_modules\←[4mnhentai-download-cli←[24m\bin\infos\extract.js:2:19) {
  code: ←[32m'ERR_PACKAGE_PATH_NOT_EXPORTED'←[39m
}
```

How do I resolve that?
